  
#From https://github.com/ProjectHDS/Herodotus/blob/master/.github/workflows/dev.yml

name: black
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
env:
  BUILD: IsolatedCrystalRemaker
  VERSION: 0.0.1

jobs:
  CreateCursePack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run build.sh
        run: bash build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD }}-${{ env.VERSION }}.${{ github.run_number }}
          path: artifacts
